<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Представляем вашему вниманию каталог интернет-магазина Фризар.");
$APPLICATION->SetPageProperty("title", "Каталог товаров");
$APPLICATION->SetTitle("Каталог");
if($_GET['ololo']=='ololo')
	exit(2);
?>


	<?$APPLICATION->IncludeComponent(
	"alexkova.market:catalog", 
	"_new_catalog", 
	array(
		"COMPATIBLE_MODE" => "Y",
		"ACTION_VARIABLE" => "action",
		"ADDITIONAL_DETAIL_INFO" => "/include/additional_detail_info.php",
		"ADDITIONAL_SKU_PIC_2_SLIDER" => "Y",
		"ADDITIONAL_TAB_SHOW" => "N",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PICT_PROP" => "MORE_PHOTO",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALSO_BUY_ELEMENT_COUNT" => "3",
		"ALSO_BUY_MIN_BUYES" => "1",
		"ALSO_BUY_TITLE" => "С этим товаром покупают",
		"ANOUNCE_TRUNCATE_LEN" => "",
		"ARTICLE_POSITION" => "none",
		"BASKET_URL" => "/personal/basket/",
		"BESTSALLERS_CNT" => "3",
		"BESTSALLERS_SORT" => "200",
		"BESTSALLERS_TITLE" => "Лидеры продаж",
		"BESTSALLERS_WERE_SHOW" => "bottom",
		"BIG_DATA_CNT" => "3",
		"BIG_DATA_RCM_TYPE" => "bestsell",
		"BIG_DATA_TITLE" => "Персональные рекомендации",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "A",
		"CATALOG_CAN_BUY_ZERO" => "Y",
		"CATALOG_DEFAULT_SORT" => "",
		"CATALOG_DEFAULT_SORT_ORDER" => "asc",
		"CATALOG_VIEW_SHOW" => "Y",
		"CHANGE_TITLE_SKU" => "N",
		"CHECK_DATES" => "N",
		"CHILD_MENU_TYPE" => "left_catalog",
		"COMMON_ADD_TO_BASKET_ACTION" => "ADD",
		"COMMON_SHOW_CLOSE_POPUP" => "N",
		"COMPARE_ELEMENT_SORT_FIELD" => "sort",
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",
		"COMPARE_FIELD_CODE" => array(
			0 => "NAME",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"COMPARE_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"COMPARE_POSITION" => "top left",
		"COMPARE_POSITION_FIXED" => "Y",
		"COMPARE_PROPERTY_CODE" => array(
			0 => "DIAMETR",
			1 => "CML2_ARTICLE",
			2 => "CML2_BASE_UNIT",
			3 => "CML2_MANUFACTURER",
			4 => "CML2_TRAITS",
			5 => "CML2_TAXES",
			6 => "CML2_ATTRIBUTES",
			7 => "CML2_BAR_CODE",
			8 => "",
		),
		"COMPARE_SCROLL_UP" => "Y",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"DEFAULT_CATALOG_VIEW" => "TITLE",
		"DELAY" => "N",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "Y",
		"DETAIL_ADD_DETAIL_TO_SLIDER_SKU" => "Y",
		"DETAIL_ADD_TO_BASKET_ACTION" => array(
		),
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "Y",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"DETAIL_BLOG_USE" => "Y",
		"DETAIL_BRAND_PROP_CODE" => array(
			0 => "",
			1 => "MANUFACTURER",
			2 => "",
		),
		"DETAIL_BRAND_USE" => "Y",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_DETAIL_PICTURE_MODE" => "IMG",
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "H",
		"DETAIL_DISPLAY_SHOW_FILES" => "Y",
		"DETAIL_DISPLAY_SHOW_VIDEO" => "Y",
		"DETAIL_FB_USE" => "N",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "SILENT",
			1 => "SIZE",
			2 => "COLOR",
			3 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "DIAMETR",
			1 => "DIAPAZON_IZMERENIY",
			2 => "SHAG_REZBY",
			3 => "TIP_SHTANGENTSIRKULYA",
			4 => "CML2_ARTICLE",
			5 => "DLINA_REZHUSHCHEY_CHASTI",
			6 => "WR_COATING",
			7 => "BLOG_COMMENTS_CNT",
			8 => "THREAD_PER_INCH",
			9 => "POKRYTIE",
			10 => "CML2_MANUFACTURER",
			11 => "THREAD_SIZE",
			12 => "MATERIAL",
			13 => "rating",
			14 => "CML2_TRAITS",
			15 => "CML2_TAXES",
			16 => "STANDARD",
			17 => "HOLE_TYPE",
			18 => "THREAD_TYPE",
			19 => "ACCURACY",
			20 => "CML2_ATTRIBUTES",
			21 => "TSENA_DELENIYA",
			22 => "THREAD_STEP",
			23 => "CML2_BAR_CODE",
			24 => "MATERIAL_1",
			25 => "NAPRAVLENIE_REZANIYA",
			26 => "OKHLAZHDENIE",
			27 => "RAZMER_SW",
			28 => "OBSHCHAYA_DLINA",
			29 => "DOPUSK",
			30 => "BREND",
			31 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "Y",
		"DETAIL_SHOW_BASIS_PRICE" => "Y",
		"DETAIL_SHOW_MAX_QUANTITY" => "Y",
		"DETAIL_STRICT_SECTION_CHECK" => "N",
		"DETAIL_USE_COMMENTS" => "Y",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DETAIL_VK_API_ID" => "API_ID",
		"DETAIL_VK_USE" => "N",
		"DETAIL_VOTE_DISPLAY_AS_RATING" => "vote_avg",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_ELEMENT_COUNT" => "Y",
		"DISPLAY_ELEMENT_SELECT_BOX" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => array(
		),
		"ELEMENT_SORT_FIELD2" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "asc",
		"FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "arrFilter2",
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PRICE_CODE" => array(
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "DIAMETR",
			1 => "DIAPAZON_IZMERENIY",
			2 => "SHAG_REZBY",
			3 => "GRUPPA_OBRABATYVAEMYKH_MATERIALOV",
			4 => "STANDART",
			5 => "TIP_SHTANGENTSIRKULYA",
			6 => "CML2_ARTICLE",
			7 => "CML2_BASE_UNIT",
			8 => "DLINA_REZHUSHCHEY_CHASTI",
			9 => "WR_COATING",
			10 => "THREAD_SIZE",
			11 => "MATERIAL",
			12 => "STANDARD",
			13 => "HOLE_TYPE",
			14 => "THREAD_TYPE",
			15 => "ACCURACY",
			16 => "CML2_ATTRIBUTES",
			17 => "TSENA_DELENIYA",
			18 => "THREAD_STEP",
			19 => "MATERIAL_1",
			20 => "NAPRAVLENIE_REZANIYA",
			21 => "OKHLAZHDENIE",
			22 => "RAZMER_SW",
			23 => "OBSHCHAYA_DLINA",
			24 => "DOPUSK",
			25 => "BREND",
			26 => "SNYAT_S_PROIZVODSTVA",
			27 => "",
		),
		"FILTER_SKU_PHOTO" => "N",
		"FILTER_VIEW_MODE" => "VERTICAL",
		"FORUM_ID" => "",
		"GIFTS_HIDE_NOT_AVAILABLE" => "Y",
		"GROUP_PRICE_COUNT" => "price",
		"HANDLERS" => array(
			0 => "lj",
			1 => "twitter",
			2 => "vk",
			3 => "mailru",
			4 => "delicious",
		),
		"HIDE_FILTER_MOBILE" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_OFFERS_LIST" => "N",
		"HIDE_PREVIEW_PROPS_INLIST" => "Y",
		"HOVER_MENU_COL_LG" => isset($arLeftMenu["HOVER_MENU_COL_LG"])?$arLeftMenu["HOVER_MENU_COL_LG"]:"2",
		"HOVER_MENU_COL_MD" => isset($arLeftMenu["HOVER_MENU_COL_MD"])?$arLeftMenu["HOVER_MENU_COL_MD"]:"2",
		"HOVER_MENU_COL_SM" => "1",
		"HOVER_MENU_COL_XS" => "1",
		"HOVER_TEMPLATE" => isset($arLeftMenu["HOVER_TEMPLATE"])?$arLeftMenu["HOVER_TEMPLATE"]:"classic",
		"IBLOCK_ID" => "17",
		"IBLOCK_TYPE" => "catalog",
		"INCLUDE_SUBSECTIONS" => "Y",
		"IN_STOCK" => "В наличии",
		"LABEL_PROP" => "-",
		"LEFT_MENU_TEMPLATE" => "left",
		"LINE_ELEMENT_COUNT" => "3",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"LINK_IBLOCK_ID" => "13",
		"LINK_IBLOCK_TYPE" => "content",
		"LINK_PROPERTY_SID" => "ACCESSORIES",
		"LIST_BROWSER_TITLE" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_META_KEYWORDS" => "-",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"LIST_OFFERS_LIMIT" => "5",
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "SILENT",
			1 => "SIZE",
			2 => "COLOR",
			3 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "METAL_DETECTOR",
			2 => "INSULATION",
			3 => "SUVENIR_NAZNACH",
			4 => "WIDTH",
			5 => "LENGHT",
			6 => "SIZE",
			7 => "HEIGHT",
			8 => "RECOMMEND",
			9 => "",
		),
		"MAIN_TITLE" => "Наличие на складах",
		"MAX_LEVEL" => "1",
		"MESSAGES_PER_PAGE" => "10",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_REQUEST" => "Поставляется под заказ",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"MIN_AMOUNT" => "3",
		"NOT_IN_STOCK" => "Нет в наличии",
		"NO_TABS" => "N",
		"NO_WORD_LOGIC" => "Y",
		"OFFERS_CART_PROPERTIES" => array(
			0 => "SIZE",
			1 => "COLOR",
		),
		"OFFERS_SORT_FIELD" => "shows",
		"OFFERS_SORT_FIELD2" => "shows",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "asc",
		"OFFERS_VIEW" => "SELECT",
		"OFFER_ADD_PICT_PROP" => "-",
		"OFFER_PRICE_SHOW_FROM" => "Y",
		"OFFER_TREE_PROPS" => array(
			0 => "COLOR",
			1 => "SIZE",
		),
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "Y",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "21",
		"PAGE_ELEMENT_COUNT_LIST" => array(
			0 => "",
			1 => "",
		),
		"PAGE_ELEMENT_COUNT_SHOW" => "Y",
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"PICTURE_CATEGARIES" => isset($arLeftMenu["PICTURE_CATEGARIES"])?$arLeftMenu["PICTURE_CATEGARIES"]:"N",
		"PICTURE_SECTION" => "N",
		"PICTURE_SECTION_HOVER" => isset($arLeftMenu["PICTURE_SECTION_HOVER"])?$arLeftMenu["PICTURE_SECTION_HOVER"]:"N",
		"PREVIEW_DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "COLOR",
			2 => "CML2_ATTRIBUTES",
			3 => "",
		),
		"PREVIEW_TRUNCATE_LEN" => "",
		"PRICE_CODE" => array(
			0 => "Продажи через сайт РУБ",
			1 => "Продажи через сайт EUR",
			2 => "Продажи через сайт CNY",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_DISPLAY_MODE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPS_TAB_VIEW" => "TABLE",
		"QTY_LESS_GOODS_TEXT" => "мало",
		"QTY_MANY_GOODS_INT" => "3",
		"QTY_MANY_GOODS_TEXT" => "много",
		"QTY_SHOW_TYPE" => "NUM",
		"RCM_COUNT_DETAIL" => "3",
		"RCM_NAME_DETAIL" => "Персональные рекомендации",
		"RCM_TYPE_DETAIL" => "similar_sell",
		"RESTART" => "Y",
		"REVIEW_AJAX_POST" => "N",
		"ROOT_MENU_TYPE" => "left_catalog",
		"SECTIONS_MAIN_VIEW_MODE" => "LIST",
		"SECTIONS_SHOW_DESCRIPTION" => "N",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"SECTIONS_VIEW_MODE" => "LIST",
		"SECTION_ADD_TO_BASKET_ACTION" => "BUY",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_ID_VARIABLE" => "SECTION_CODE",
		"SECTION_TOP_DEPTH" => "2",
		"SEF_FOLDER" => "/catalog/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHORTEN_URL_KEY" => "",
		"SHORTEN_URL_LOGIN" => "",
		"SHOWS_BIGDATA_DETAIL" => "Y",
		"SHOW_404" => "Y",
		"SHOW_CATALOG_QUANTITY" => "Y",
		"SHOW_CATALOG_QUANTITY_CNT" => "Y",
		"SHOW_DEACTIVATED" => "N",
		"SHOW_DESCRIPTION_AFTER_SECTION" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_EMPTY_STORE" => "Y",
		"SHOW_GENERAL_STORE_INFORMATION" => "Y",
		"SHOW_LEFT_CATALOG_MENU" => "Y",
		"SHOW_LEFT_MENU" => "Y",
		"SHOW_LEFT_MENU_SETTINGS" => "Y",
		"SHOW_LINK_TO_FORUM" => "N",
		"SHOW_MAIN_INSTEAD_NF_SKU" => "N",
		"SHOW_MEASURE" => "Y",
		"SHOW_OFFER_PIC_BYCLICK" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_PRICE_NAME" => "N",
		"SHOW_SECTION_DESC" => "top",
		"SHOW_SECTION_SEO" => "N",
		"SHOW_TOP_ELEMENTS" => "Y",
		"SIDEBAR_DETAIL_SHOW" => "Y",
		"SIDEBAR_PATH" => "",
		"SIDEBAR_SECTION_SHOW" => "Y",
		"SKU_PROPS_SHOW_TYPE" => "rounded",
		"SKU_SORT_PARAMS" => "N",
		"STORES" => array(
			0 => "1",
		),
		"STORE_PATH" => "/company/#store_id#",
		"STYLE_MENU" => "colored_light",
		"STYLE_MENU_HOVER" => isset($arLeftMenu["STYLE_MENU_HOVER"])?$arLeftMenu["STYLE_MENU_HOVER"]:"colored_light",
		"SUBMENU" => "ACTIVE_SHOW",
		"TEMPLATE_THEME" => "site",
		"THEME" => "default",
		"TILE_SHOW_PROPERTIES" => "N",
		"TITLE_MENU" => "Каталог",
		"TOP_ADD_TO_BASKET_ACTION" => "BUY",
		"TOP_ELEMENT_COUNT" => "2",
		"TOP_ELEMENT_SORT_FIELD" => "shows",
		"TOP_ELEMENT_SORT_FIELD2" => "shows",
		"TOP_ELEMENT_SORT_ORDER" => "asc",
		"TOP_ELEMENT_SORT_ORDER2" => "asc",
		"TOP_LINE_ELEMENT_COUNT" => "3",
		"TOP_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_LIMIT" => "5",
		"TOP_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_ROTATE_TIMER" => "30",
		"TOP_TITLE" => "Лидеры продаж",
		"TOP_VIEW_MODE" => "BANNER",
		"URL_TEMPLATES_READ" => "",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"USE_ALSO_BUY" => "Y",
		"USE_BIG_DATA" => "Y",
		"USE_CAPTCHA" => "Y",
		"USE_COMMON_SETTINGS_BASKET_POPUP" => "Y",
		"USE_COMPARE" => "Y",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_EXT" => "Y",
		"USE_FAVORITES" => "Y",
		"USE_FAVORITES_TEXT" => "Избранное",
		"USE_FILTER" => "Y",
		"USE_GIFTS_DETAIL" => "N",
		"USE_GIFTS_SECTION" => "N",
		"USE_LANGUAGE_GUESS" => "N",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_MIN_AMOUNT" => "Y",
		"USE_ONE_CLICK" => "Y",
		"USE_ONE_CLICK_TEXT" => "Купить в 1 клик",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"USE_REVIEW" => "Y",
		"USE_SALE_BESTSELLERS" => "Y",
		"USE_SHARE" => "Y",
		"USE_SHARE_TEXT" => "Поделиться",
		"USE_STORE" => "N",
		"USE_STORE_PHONE" => "Y",
		"USE_STORE_SCHEDULE" => "Y",
		"VIDEO_PLAYER" => "MEJ",
		"VIDEO_PLAYER_FULLSCREEN" => "N",
		"VIDEO_TYPE" => "GRID",
		"VIEWED_PRODUCTS_BLOCK_TITLE" => "Просмотренные товары",
		"VIEWED_PRODUCTS_CNT" => "3",
		"VIEWED_PRODUCTS_SHOW" => "Y",
		"VIEWED_PRODUCTS_SORT" => "100",
		"VIEWED_PRODUCTS_WERE_SHOW" => "left",
		"ZOOM_ON" => "Y",
		"COMPONENT_TEMPLATE" => "_new_catalog",
		"ELEMENT_SORT_FIELD_BOX" => "sort",
		"ELEMENT_SORT_ORDER_BOX" => "asc",
		"ELEMENT_SORT_FIELD_BOX2" => "id",
		"ELEMENT_SORT_ORDER_BOX2" => "asc",
		"FILE_404" => "",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"SHOW_ANALOG_BTN" => "Y",
		"CACHE_NOTES" => "",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
			"compare" => "/catalog/compare/index.php?action=#ACTION_CODE#",
			"smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);?>



<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
